# Generated by Django 5.2.5 on 2025-08-16 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missingperson',
            options={'ordering': ['disappearance_date']},
        ),
        migrations.AlterModelOptions(
            name='searcher',
            options={'ordering': ['created_at']},
        ),
        migrations.AddField(
            model_name='searcher',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
