# Generated by Django 5.2.5 on 2025-08-16 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finder', '0002_alter_missingperson_options_alter_searcher_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='missingperson',
            options={'ordering': ['-disappearance_date']},
        ),
        migrations.AlterModelOptions(
            name='searcher',
            options={'ordering': ['-created_at']},
        ),
    ]
